// SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;

import {Test} from "forge-std/Test.sol";
import {KeyRegistry} from "../src/KeyRegistry.sol";
import {OidcRecoveryGuardian} from "../src/OidcRecoveryGuardian.sol";
import {IUltraHonkVerifier} from "../src/interfaces/IUltraHonkVerifier.sol";
import {IGuardianLogic} from "../src/interfaces/IGuardianLogic.sol";

/// @notice Unlike OidcRecoveryGuardian.t.sol (which deliberately uses MockVerifier to isolate
///         the guardian's OWN checks, per that file's header comment), this test replaces the
///         mock with the actual `bb write_solidity_verifier` output
///         (circuits/jwt-recovery/verifier/src/JwtRecoveryVerifier.sol) and feeds it an actual
///         proof generated by the actual circuit from an actual RSA-2048/RS256-signed JWT
///         (circuits/jwt-recovery/js/generate-test-vector.mjs). This is the "replace the mock in
///         tests" step from .superpowers/specs/2026-08-18-keyregistry-spec.md's "What's built vs.
///         what's left" section, now done: OidcRecoveryGuardian.submitRecoveryApproval runs
///         end-to-end against real cryptography, not a boolean stand-in.
///
///         The verifier can't be `new`'d here directly: circuits/jwt-recovery/verifier is its own
///         Foundry project (see that project's foundry.toml for why — solc's Yul optimizer hits a
///         stack-too-deep error on bb's generated code under this project's via_ir=true/
///         prague/200-runs settings, regardless of runs count). Its compiled artifact is loaded
///         via vm.getCode instead, which is exactly what that separation is for: the rest of the
///         stack only needs this contract's bytecode and the IUltraHonkVerifier-compatible ABI,
///         never its source.
contract RealVerifierIntegrationTest is Test {
    // circuits/jwt-recovery/js/generate-test-vector.mjs baked these exact values into the JWT
    // (nonce = 0x1b43…3479's hex encoding) and proof (pubkeyHash, identity) it produced, so this
    // wallet/promoteKey/chainid/nonce combination is fixed — regenerating the test vector with
    // different values means regenerating this file's constants together, not independently.
    address constant WALLET = 0x1111111111111111111111111111111111111111;
    address constant PROMOTE_KEY = 0x2222222222222222222222222222222222222222;
    uint64 constant NONCE = 7;
    uint256 constant CHAIN_ID = 84532; // Base Sepolia

    bytes32 constant PUBKEY_HASH = 0x0f488f95ec3fd8596e2fb345d5bbb81925ce6d53a91fac65561a79179cef8dc8;
    bytes32 constant IDENTITY = 0x0ff1422ab7b06df8e080e0d419c6780223f8cd05468c5c9edadce603ad7e2583;

    string constant ISSUER = "https://accounts.google.com";
    string constant KID = "test-kid-1";

    address owner = makeAddr("owner");
    address a1 = makeAddr("a1");
    address a2 = makeAddr("a2");

    KeyRegistry registry;
    OidcRecoveryGuardian oidc;

    function setUp() public {
        vm.chainId(CHAIN_ID);

        address[] memory attestors = new address[](2);
        attestors[0] = a1;
        attestors[1] = a2;
        registry = new KeyRegistry(owner, attestors, 2, 1 hours, 2 days);

        vm.prank(a1);
        registry.attest(ISSUER, KID, PUBKEY_HASH);
        vm.prank(a2);
        registry.attest(ISSUER, KID, PUBKEY_HASH);
        vm.warp(block.timestamp + 1 hours + 1);

        bytes memory verifierArtifact =
            vm.getCode("circuits/jwt-recovery/verifier/out/JwtRecoveryVerifier.sol/HonkVerifier.json");
        address verifierAddr;
        assembly {
            verifierAddr := create(0, add(verifierArtifact, 0x20), mload(verifierArtifact))
        }
        require(verifierAddr != address(0), "verifier deploy failed");

        oidc = new OidcRecoveryGuardian(registry, IUltraHonkVerifier(verifierAddr));

        // No real GuardianLogic wallet exists at the fixed WALLET address the proof was bound to
        // (its nonceBinding public input is keccak256(WALLET, PROMOTE_KEY, NONCE, CHAIN_ID) and
        // can't be regenerated post hoc) — GuardianLogic.t.sol and OidcRecoveryGuardian.t.sol
        // already cover that threshold/timelock chain exhaustively with MockVerifier. What this
        // test adds is the proof-verification path, so WALLET only needs to accept the final
        // approveRecovery(address,uint64) call, not run a real wallet.
        vm.etch(WALLET, type(ApprovalSink).runtimeCode);
        vm.prank(WALLET); // setRecoveryIdentity is wallet-initiated (msg.sender-keyed)
        oidc.setRecoveryIdentity(IDENTITY);
    }

    function test_submitRecoveryApproval_acceptsRealProofFromRealCircuit() public {
        bytes memory proof = vm.readFileBinary("circuits/jwt-recovery/target/proof");
        bytes memory rawPublicInputs = vm.readFileBinary("circuits/jwt-recovery/target/public_inputs");
        require(rawPublicInputs.length == 96, "unexpected public_inputs length");

        bytes32[] memory publicInputs = new bytes32[](3);
        for (uint256 i = 0; i < 3; i++) {
            bytes32 word;
            uint256 offset = 32 + i * 32; // skip the bytes-length word ABI encoding adds
            assembly {
                word := mload(add(rawPublicInputs, offset))
            }
            publicInputs[i] = word;
        }
        assertEq(publicInputs[0], PUBKEY_HASH, "pubkeyHash public input mismatch");
        assertEq(publicInputs[1], IDENTITY, "identity public input mismatch");

        oidc.submitRecoveryApproval(WALLET, PROMOTE_KEY, NONCE, ISSUER, KID, PUBKEY_HASH, proof, publicInputs);

        assertEq(ApprovalSink(WALLET).lastPromoteKey(), PROMOTE_KEY);
        assertEq(ApprovalSink(WALLET).lastNonce(), NONCE);
    }

    function test_submitRecoveryApproval_rejectsTamperedProof() public {
        bytes memory proof = vm.readFileBinary("circuits/jwt-recovery/target/proof");
        proof[0] = proof[0] ^ bytes1(uint8(1)); // flip one bit of the real proof

        bytes32[] memory publicInputs = new bytes32[](3);
        publicInputs[0] = PUBKEY_HASH;
        publicInputs[1] = IDENTITY;
        publicInputs[2] = keccak256(abi.encode(WALLET, PROMOTE_KEY, NONCE, CHAIN_ID))
            & bytes32((uint256(1) << 253) - 1);

        vm.expectRevert();
        oidc.submitRecoveryApproval(WALLET, PROMOTE_KEY, NONCE, ISSUER, KID, PUBKEY_HASH, proof, publicInputs);
    }
}

/// @dev Minimal IGuardianLogic.approveRecovery sink standing in for a real wallet, deployed via
///      vm.etch at the exact address the proof's nonceBinding is bound to (see WALLET above).
contract ApprovalSink {
    address public lastPromoteKey;
    uint64 public lastNonce;

    function approveRecovery(address promoteKey, uint64 nonce) external {
        lastPromoteKey = promoteKey;
        lastNonce = nonce;
    }
}
